services:
  - type: web
    name: web-terminal
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: AUTH_TOKEN
        sync: false
      - key: NODE_ENV
        value: production
